### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by BrixSat** [Wutze/OpenVPN-WebAdmin#26]
You are assuming this will be installed in the http://<ip>/ of a root dir. Its not correct to assume that. I in my case will be using this in http://<ip>/ovpn/.

Missing in forms the path.

**Comment by Wutze** [comment]
That is correct that I install the system in principle in the Webroot and do not currently offer any other option, nor do I have any plans to do so. At the moment, I don't know any reason why I should change this, as access to the network via VPN should be done via a separate VPN server anyway. This is a complete system, not a web hosting.

In addition, the system would be brought into an unstable state, as system-relevant files are made available for viewing and editing. Since SSL keys are also to be generated and stored in the future, a change to this system would also be counterproductive in terms of system security.

The specification of your URL with http:/// is also misleading.

The correct URL would be (http|s)://(IP|FQDN)/

I will say it again at the end, this is a complete system consisting of the server software OpenVPN with a "simple" web administration of the user access. Anyone who also wants to use the system for other purposes, such as hosting private websites, should consider taking the "security" issue lightly.

Translated with www.DeepL.com/Translator (free version)
