### ISSUE TITLE
install.sh

### ISSUE THREAD

**Issue by virusczz** [Wutze/OpenVPN-WebAdmin#27]
Hi, this is so cool, i want also :) but unfortunitly i have a problem :(

i filled all, and started the install

result stop:
ERROR 1305 (42000) at line 1: FUNCTION openvpnadmin.encrypt does not exist
 [✗] Error Insert Webadmin User

using ubuntu 20.4 server

**Comment by Wutze** [comment]
The whole thing hasn't been tested under Ubuntu yet, but I'll take a look at it anyway. Nevertheless, please note, only for 
    Debian 10/Buster, PHP 7.2.x, 10.3.22-MariaDB.
    RaspberryPi 4 with Debian Buster
    CentOS 8
If I find a simple solution, I'll let you know here.

**Comment by Wutze** [comment]
I could not reproduce the error. One possible cause could be the "**&**" character in the password. This is translated incorrectly in the script and leads to errors.

**Comment by Wutze** [comment]
After today's update of the script to yarn 12.x, I tested the installation again. It ran without problems under Ubuntu 20.04.2.

I think the problem should be solved now.

**Comment by virusczz** [comment]
> The whole thing hasn't been tested under Ubuntu yet, but I'll take a look at it anyway. Nevertheless, please note, only for
> Debian 10/Buster, PHP 7.2.x, 10.3.22-MariaDB.
> RaspberryPi 4 with Debian Buster
> CentOS 8
> If I find a simple solution, I'll let you know here.

i know, i was thinking debian is the base for ubuntu ;) will be easyer to update to this distro, redhat is different ;)

i like the project and i want to use it :)

**Comment by virusczz** [comment]
> I could not reproduce the error. One possible cause could be the "**&**" character in the password. This is translated incorrectly in the script and leads to errors.

no the password is only with Xxxxxxx/####  where X = char and # number and / sysmbol not the & but the / thi ca ndo also some problem ?

**Comment by virusczz** [comment]
i gived a new try and with remove (localhost) mysql:

[▸ Select Language ◂]
 [✓] Set Language to: en_EN
 [✓] Root user check
 [▸ Install on:  debian  ◂]
 [▸ Set Parameters Webserver ◂]
 [▸ define Owner for permissions ◂]
 [✓] define permissions on debian : www-data:www-data
 [✓] Intro Attention
 [▸ Press ENTER to start the installation or ctrl+c to cancel ◂]
 【ツ】
 [✓] Select the installationoptions:
 [▸ give me inputs ◂]
 [✓] Execution Ok: do_select
 [▸ copy install.config ◂]
 [✓] Execution Ok: copy config.conf
 [▸ define selectet SQL-Server|SQL-Client ◂]
 [✓] Install Client on debian: default-mysql-client
 [✓] Fin selection
 [▸ check install-config ◂]
 [✓] read install-config
 [▸ checks if all required programs are installed ◂]
 [▸ Setup the variables ◂]
 [✓] Execution Ok: Server IP
 [✓] Execution Ok: VPN Protokoll
 [✓] Execution Ok: OpenVPN Port
 [✓] Execution Ok: DB-Host
 [✓] Execution Ok: DB-Name
 [✓] Execution Ok: Root PW
 [✓] Execution Ok: MySQL Username
 [✓] Execution Ok: MySQL User PW
 [✓] Execution Ok: Web Admin User
 [✓] Execution Ok: Web Admin PW
 [✓] the setup have all variables now
 [▸ Setup Database ◂]
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1305 (42000) at line 1: FUNCTION openvpnadmin.encrypt does not exist
 [✗] Error Insert Webadmin User

**Comment by virusczz** [comment]
and this was with localinstall of mysql:
[▸ Select Language ◂]
 [✓] Set Language to: en_EN
 [✓] Root user check
 [▸ Install on:  debian  ◂]
 [▸ Set Parameters Webserver ◂]
 [▸ define Owner for permissions ◂]
 [✓] define permissions on debian : www-data:www-data
 [✓] Intro Attention
 [▸ Press ENTER to start the installation or ctrl+c to cancel ◂]
 【ツ】
 [✓] Select the installationoptions:
 [▸ give me inputs ◂]
 [✓] Execution Ok: do_select
 [▸ copy install.config ◂]
 [✓] Execution Ok: copy config.conf
 [▸ define selectet SQL-Server|SQL-Client ◂]
 [✓] Install Server on debian: mariadb-server
 [▸ define selectet Webserver ◂]
 [✓] Install on debian: apache2
 [✓] Fin selection
 [▸ check install-config ◂]
 [✓] read install-config
 [▸ checks if all required programs are installed ◂]
 [▸ Insert/Set MySQL Root PW ◂]
 [✓] Execution Ok: input mysql root pw
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by '*******' with grant option' at line 1
mysql: [Warning] Using a password on the command line interface can be insecure.
 [✓] Execution Ok: set mysql root pw
 [▸ Setup the variables ◂]
 [✓] Execution Ok: Server IP
 [✓] Execution Ok: VPN Protokoll
 [✓] Execution Ok: OpenVPN Port
 [✓] Execution Ok: DB-Host
 [✓] Execution Ok: DB-Name
 [✓] Execution Ok: Root PW
 [✓] Execution Ok: MySQL Username
 [✓] Execution Ok: MySQL User PW
 [✓] Execution Ok: Web Admin User
 [✓] Execution Ok: Web Admin PW
 [✓] the setup have all variables now
 [▸ Setup User Password for OpenVPN-WebAdmin on your DB-Server ◂]
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY '********'' at line 1
 [✗] Execution break: Create local Database

**Comment by Wutze** [comment]
2021-03-22:21.30.52: Insert/Set MySQL Root PW
2021-03-22:21.31.11: Execution Ok: input mysql root pw
2021-03-22:21.31.11: Execution Ok: set mysql root pw
2021-03-22:21.31.11: Setup the variables
2021-03-22:21.31.18: Execution Ok: Server IP
2021-03-22:21.31.20: Execution Ok: VPN Protokoll
2021-03-22:21.31.21: Execution Ok: OpenVPN Port
2021-03-22:21.31.22: Execution Ok: DB-Host
2021-03-22:21.31.24: Execution Ok: DB-Name
2021-03-22:21.31.25: Execution Ok: Root PW
2021-03-22:21.31.30: Execution Ok: MySQL Username
2021-03-22:21.31.32: Execution Ok: MySQL User PW
2021-03-22:21.31.35: Execution Ok: Web Admin User
2021-03-22:21.31.38: Execution Ok: Web Admin PW
2021-03-22:21.31.38: the setup have all variables now
2021-03-22:21.31.38: Setup User Password for OpenVPN-WebAdmin on your DB-Server
2021-03-22:21.31.38: Execution Ok: Create local Database
2021-03-22:21.31.38: Setup Database
2021-03-22:21.31.41: setting up MySQL OK
2021-03-22:21.31.41: Creating the certificates
2021-03-22:21.31.42: Setup OpenVPN
2021-03-22:21.31.42: Init PKI dirs and build CA certs
2021-03-22:21.31.56: Generate Diffie-Hellman parameters

Installed with Ubuntu 20.04.2 LTS
This is my extract from the log file from just now. (/opt/[ Git-Folder ]/loginstall.log) Unfortunately, I cannot reproduce the error, which makes it impossible for me to search for it for the time being. Sorry.

Unfortunately, Ubuntu differs from Debian in some things. Ubuntu is too fast-moving for me, which is why I only use Debian, Raspian or CentOS.

**Comment by Wutze** [comment]
The following proposal, which would then work.

First install the MySQL server, create a WebVPN user and an empty database, give it the necessary rights and then select the remote MaySQL during the installation and enter the necessary data.

This should then work without any problems. Unfortunately, I can't find any other way at the moment, as I still can't reproduce the error.

**Comment by virusczz** [comment]
do i need to run this in /opt/ folder ? i am running this in /root/ folter (i am logged like root)

**Comment by virusczz** [comment]
i made a clean install. instaled open-vpn, mariadb all ok
suggetion:  ask for the user with root privilegies :) (i don't accept rooc connections, i made a user fro that)

all running finaly 

but now i can do what i want but no new user added :(

**Comment by Wutze** [comment]
It would never have occurred to me to install it from there, but no, that shouldn't cause this problem either. It works sudo ./install.sh as well as sudo -i to then start the installation. No matter what folder the git has been checked out to.

But a newly installed MySQL server has a root user. However, since this is not yet set up, when reinstalling a local SQL server, it must of course be created. Only then is a user created with the rights that the WebAdmin needs.

I suspect that this is where you are making the mistake. Because the OpenVPN WebAdmin does not use root rights to work, the installation script only needs these to create a user so that the WebAdmin can work with these reduced rights. unless you already have a pre-configured MySQL server, then you only have to select "Remote-mySQL". A prepared database with a user for it, who also has the rights to create/modify tables, provided. The tables are then created during the installation, not before.

I have just tested again. Checked out the repository in the root folder, no problem. I cannot understand your error. I am sincerely sorry. You seem to have made changes to the system to suit your security needs before installation. You may even already have a firewall running that restricts access to MySQL. Unfortunately, I don't know.

**Comment by virusczz** [comment]
i already passad all problems :) 
i added to install all, was some problems with adding new user :(, but resolved :).
i reinstaled all :), and now with all (full install)
Now i am strugling with:
 1. don't see the Debug tab
 2. firewall tab
 3. system tab
 4. dev tab

**Comment by virusczz** [comment]
i changed the server to debian 10
still don't see:
don't see the 

Debug tab
firewall tab
system tab
dev tab

**Comment by Wutze** [comment]
I'll quote the end of the installation routine that said:

MOENABLE0="You installed modules. To enable these modules, transfer the following"
MOENABLE1="information from /include/module.config.php to /include/config.php"

;o)

**Comment by Wutze** [comment]
/** 
 * only for development!
 * please comment out if no longer needed!
 * comment out the "define function" to enable
 */
if(file_exists("dev/dev.php")){
	define('dev','dev/dev.php');
}
if (defined('dev')){
	include_once('dev/class.dev.php');
}

define('firewall',TRUE);
define('system',TRUE);
define('clientload',TRUE);
