### ISSUE TITLE
Can't install - missing nodejs 12.0 in CentOS

### ISSUE THREAD

**Issue by vicn1222** [Wutze/OpenVPN-WebAdmin#29]
Hi,

I just installed Chocobozzz/OpenVPN-Admin. It works well.

I would like to try yours too because your gui look interesting. But I can't install them. It aborted with errors.

My system is CentOS 8 and it has been fully updated ("dnf update -y" has been done)

(1) I already have mariadb-server installed correctly and used by my website. Your install.sh script reset the database root password to something I don't know and I can no longer login with root. I have to uninstall mariadb-server, and delete /var/lib/mysql, then run your script again to reinstall the mariadb-server.

(2) I already have yarn installed. The script fails with message
error @stencil/core@2.5.2: The engine "node" is incompatible with this module. Expected version ">=12.10.0". Got "10.24.0" 
error Found incompatible module.
 [✗] Error yarn installed 

Can you check?

Thanks.

**Comment by vicn1222** [comment]
Finally got installed and running by doing below:

(1) Install latest nodejs following https://tecadmin.net/install-latest-nodejs-on-centos-8/
npm is included in nodejs, so I remove npm from the install.sh

(2) Change line
yum module enable nodejs:10 >> ${CURRENT_PATH}/loginstall.log

to 

yum module enable nodejs:15 -y >> ${CURRENT_PATH}/loginstall.log

"-y" was missing, causing installer to hange (wait for "y" without prompt).

(3) Fail to start openvpn because "SELinux is preventing /usr/sbin/openvpn from open access on the file /etc/openvpn/server.conf", I have to do below:

restorecon -R -v /etc/openvpn

(4) firewall is disabled. This is not good. 
I can open up openvpn service and port (1194/udp) for openvpn users to access, but not disable it to allow unrestricted access, although I have fail2ban installed.

Some comments
1. Thank you for all the effort!
2. The gui interface is shaking automatically

**Comment by vicn1222** [comment]
I reenable firewall, and open up openvpn port and service. It continues to work. So don't disable firewall.

systemctl unmask --now firewalld
systemctl enable firewalld
systemctl start firewalld
firewall-cmd --zone=public --permanent --add-service=openvpn
firewall-cmd --zone=public --permanent --add-port=1194/udp
firewall-cmd --reload


Now I do firewall-cmd --list-all

[root@t610]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eno1
  sources: 
  services: cockpit dhcpv6-client http https openvpn ssh
  ports: 443/tcp 1194/udp
  protocols: 
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:

**Comment by Wutze** [comment]
My approach is to use a "naked system" as a stand-alone VPN server. That is, without any other services on the server.

I agree with you that the installation could be made a little more elegant and ask beforehand whether and which services have been installed so that they are not touched again during the installation. However, see above, naked system ;o)

In the end, everyone can use a firewall as they wish. However, I am of the opinion that a VPN server should not be connected to the internet via a network port, but should always be behind a firewall, which supplies the VPN server with the data it needs with the appropriate rules.

The point about nodejs and version 12 was not known to me until now. The script only installs version 10. I will change this error as soon as possible. Thank you very much for this tip.

**Comment by Wutze** [comment]
If you have an installed MySQL server, then the point would have helped:

https://github.com/Wutze/OpenVPN-WebAdmin#note-mysql
