### ISSUE TITLE
no connectionn

### ISSUE THREAD

**Issue by atlants1998** [Wutze/OpenVPN-WebAdmin#31]
i followed the steps but the connection is not successful 
i`m trying with openvpn connect on windows

**Comment by Wutze** [comment]
I also always had problems with the software, which is why I went back to the "old" software.

Apparently, so my assumption (I haven't had Windows for many years), it's because of the user rights. Windows needs admin rights so that new IP addresses or the routing can be changed.

Unfortunately, I'm not much help here. Maybe someone else knows more about this. I'm sorry.

It has always worked well with this software version so far.

https://openvpn.net/downloads/openvpn-connect-v2-windows.msi

**Comment by dungpt2020** [comment]
If you're using OpenVPN Connect (on client machine) to connect VPN server, may you facing the error like below.
```
Wed Jun 30 11:01:52 2021 Wed Jun 30 11:01:52 2021 OpenVPN core 3.5.4 win x86_64 64-bit
Wed Jun 30 11:01:52 2021 Wed Jun 30 11:01:52 2021 CLIENT_EXCEPTION : connect error: Missing External PKI alias [FATAL-ERR]
Wed Jun 30 11:01:52 2021 Wed Jun 30 11:01:52 2021 >FATAL:CLIENT_EXCEPTION: connect error: Missing External PKI alias
```
This is because of OpenVPN Connect is created to working with OpenVPN Access Server (this is OpenVPN Server Premium version). So, It may not working with OpenVPN Community Server (free). I tested this client software with both and find out that.

The solution is simple, you just use OpenVPN GUI (on client machine) instead of OpenVPN Connect. There are 2 difference packages.

You can download OpenVPN GUI from this link (It's latest at current time): https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.3-I601-amd64.msi

The list packages of OpenVPN GUI: https://openvpn.net/community-downloads

**Comment by Wutze** [comment]
Hello

Thank you for this tip. I do not use the new version of the OpenVPN client in version 3.x myself, as I have only ever had problems with it. That's why I link to version 2.x in the rest of my instructions.

But thanks for the information, I will add your tip.

Thank you very much and stay healthy
