### ISSUE TITLE
Cannot Install on Centos 7

### ISSUE THREAD

**Issue by chienbinhso14** [Wutze/OpenVPN-WebAdmin#48]
I've removed the install node and yarn section because it always installs node 6.x < requirement is 8. I'd manually install node 12 before running install.sh. I also install php7.3 and php73-fpm with extensions. When I access FQDN / IP it throws a 500 error.
![image](https://user-images.githubusercontent.com/24795386/127946493-63069c77-dfd7-4c80-91b5-8c900635d569.png)

[installsh.txt](https://github.com/Wutze/OpenVPN-WebAdmin/files/6920558/installsh.txt)
[loginstall.log](https://github.com/Wutze/OpenVPN-WebAdmin/files/6920554/loginstall.log)

**Comment by Wutze** [comment]
> manually install node 12

That is correct and yes, the idea as you have executed it is a good one.

However, the error 500 seems to be an error in the configuration of the web server in connection with PHP. I suspect, I can't test it due to the lack of CentOS7, that this could be the problem. 

The libraries with node 12 are "only" the Java-Script libraries to display the website.

The log file from the installation also looks good. I can't see any errors.

Are the permissions to the webroot correct?
This ~> define permissions on centos : apache:apache

**Comment by chienbinhso14** [comment]
I'm using nginx.
I've chown nginx:nginx on wwwroot but it doesn't work.
I will try fresh install again to verify error.

**Comment by Wutze** [comment]
nginx:nginx is fine

I guess you might have problems with the fast_cgi of PHP. If I am not mistaken, you would have to install the following for this

yum -y install php-fpm php-cli
